disabled = false
locale = "en"
label = "English"
weight = 1
title = "palilo's"

[params]
displayName = "EN"
isoCode = "ko"
rtl = false
dateFormat = "2006-01-02"
description = "palilo's blog"
copyright = "© 2026 palilo"

["params.author"]
name = "palilo"
email = "palilo@protonmail.com"
