[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "G8dlEq52oU"
weight = 9_999

[[main]]
name = "About"
pageRef = "about"
identifier = "eezfHh52jm"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "TwuRJE77qW"
weight = 9_999

[[footer]]
none = "none"
