title = "palilo's"
baseURL = "https://palilo815.github.io"
theme = ["PaperMod"]

languageCode = "ko-kr"
defaultContentLanguage = "kr"

paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts", "papermod"]

[minify]
disableXML = true

[languages.kr]
languageName = ":kr:"
weight = 1

[languages.kr.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.kr.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.kr.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.kr.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = ["images/papermod-cover.png"]

[params.profileMode]
enabled = false
title = "PaperMod"
imageUrl = "#"
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Archives"
url = "archives"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "palilo's blog"
Content = """
👋 Welcome to demo page of Hugo's theme PaperMod!
- **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.
- Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .
- PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).
"""

[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/palilo815"

[params.editPost]
URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
Text = "Suggest Changes"
appendFilePath = true

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
